from __future__ import annotations

import json
import os
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import soc_store

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONTENT_PACKS_DIR = ROOT / "reports" / "content_packs"


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def content_packs_dir(custom_path: Optional[str] = None) -> Path:
    target = Path(custom_path).expanduser().resolve() if custom_path else DEFAULT_CONTENT_PACKS_DIR
    target.mkdir(parents=True, exist_ok=True)
    return target


def _clean_text(text: Any, limit: int = 5000) -> str:
    return str(text or "").strip()[:limit]


def _format_twitter_thread(case_data: Dict[str, Any]) -> str:
    title = case_data.get("title") or "Supply Chain Threat Disclosure"
    package = case_data.get("package") or "package"
    version = case_data.get("version") or ""
    ecosystem = case_data.get("ecosystem") or "npm"
    severity = str(case_data.get("severity") or "high").upper()
    summary = case_data.get("summary") or ""
    iocs = case_data.get("iocs") or []
    diff_summary = case_data.get("diff_summary") or "Obfuscated lifecycle execution detected in package manifest."

    pkg_tag = f"{package}@{version}" if version else package

    tweet1 = f"[1/5] THREAT ADVISORY: SecOpsAI has identified a malicious {ecosystem} supply-chain release: `{pkg_tag}` ({severity} severity).\n\nHere is the technical breakdown of the payload, evasion technique, and indicators:\n\n#CyberSecurity #ThreatIntel #{ecosystem.upper()} #AppSec"
    tweet2 = f"[2/5] Technical Anatomy:\n\n{summary[:240]}\n\nThe attack leverages unexpected runtime execution sinks to bypass standard static regex scanners."
    tweet3 = f"[3/5] Differential & Heuristic Findings:\n\n- Differential Delta: {diff_summary[:200]}\n\nCheck attached code diff asset (01_ast_diff.txt) for exact injection points."
    
    ioc_lines = "\n".join([f"- `{ioc}`" for ioc in iocs[:4]]) if iocs else f"- Package: `{pkg_tag}`\n- Ecosystem: `{ecosystem}`\n- Status: Confirmed Malicious"
    tweet4 = f"[4/5] Indicators of Compromise (IOCs):\n\n{ioc_lines}"
    tweet5 = f"[5/5] Mitigation & Verification:\n\nRun local verification across your repositories:\n$ secopsai refresh --platform supply_chain\n$ secopsai correlate\n\nFull disclosure report generated by SecOpsAI Research."

    return "\n\n---\n\n".join([tweet1, tweet2, tweet3, tweet4, tweet5])


def _format_reddit_post(case_data: Dict[str, Any]) -> str:
    title = case_data.get("title") or "Supply Chain Threat Disclosure"
    package = case_data.get("package") or "package"
    version = case_data.get("version") or ""
    ecosystem = case_data.get("ecosystem") or "npm"
    summary = case_data.get("summary") or ""
    iocs = case_data.get("iocs") or []
    evidence = case_data.get("evidence") or []
    pkg_tag = f"{package}@{version}" if version else package

    evd_lines = "\n".join([f"  - {item}" for item in evidence[:6]]) if evidence else "  - Suspicious lifecycle execution hook\n  - Dynamic eval / outbound network behavior"
    ioc_table = "\n".join([f"| Network / Hash | `{ioc}` |" for ioc in iocs]) if iocs else f"| Package | `{pkg_tag}` |"

    post = f"""# [Technical Analysis] Dissecting supply-chain threat in {ecosystem} package `{pkg_tag}`

**Target**: `{pkg_tag}` ({ecosystem})  
**Detection Engine**: SecOpsAI AST Differential Research Monitor  
**Severity**: {str(case_data.get("severity") or "High").title()}  

---

### 1. Executive Summary
During automated ingestion and comparative differential analysis, an anomalous supply-chain payload was detected in `{pkg_tag}`. 

{summary}

---

### 2. Reverse Engineering & Static AST Breakdown
- **Ecosystem**: `{ecosystem}`
- **Suspect Package**: `{pkg_tag}`
- **Baseline Comparison**: {case_data.get("baseline_version") or "Prior release / Clean baseline"}
- **Heuristic Indicators**:
{evd_lines}

---

### 3. Indicators of Compromise (IOCs)
| Type | Value |
| :--- | :--- |
{ioc_table}

---

### 4. Reproduction & Local Verification
To audit your own infrastructure and local workspaces against this package:

```bash
# Refresh supply-chain telemetry
secopsai refresh --platform supply_chain

# Check local dependency trees
secopsai check --ecosystem {ecosystem} --package {package}
```

*Published via SecOpsAI Research Collective.*
"""
    return post.strip()


def _format_linkedin_post(case_data: Dict[str, Any]) -> str:
    package = case_data.get("package") or "package"
    version = case_data.get("version") or ""
    ecosystem = case_data.get("ecosystem") or "npm"
    pkg_tag = f"{package}@{version}" if version else package
    summary = case_data.get("summary") or ""

    post = f"""Supply Chain Security Update: Threat Detected in {ecosystem} package `{pkg_tag}`

Software supply-chain risks continue to evolve beyond simple dependency confusion into sophisticated lifecycle hooks and AST-evading payloads.

Our automated research pipeline at SecOpsAI recently flagged and isolated `{pkg_tag}`:

Key Takeaways for Engineering & Security Leaders:
- Attack Pattern: {summary[:280]}
- Evasion Technique: Targeted execution during package initialization designed to evade traditional signature-based scanners.
- Proactive Defense: Continuous differential analysis (comparing AST deltas between package releases) is crucial to intercept zero-day package tampering before it reaches production CI/CD pipelines.

Full IOCs and remediation steps have been packaged by our research pipeline.

#CyberSecurity #ApplicationSecurity #AppSec #SupplyChainSecurity #InfoSec #DevSecOps #OpenSourceSecurity
"""
    return post.strip()


def generate_content_pack(
    case_id: str,
    *,
    db_path: Optional[str] = None,
    output_dir: Optional[str] = None,
) -> Dict[str, Any]:
    """Generate a full social media & community content pack for a research case or finding."""
    soc_store.init_db(db_path)
    clean_id = _clean_text(case_id, 80).upper()

    case_data: Dict[str, Any] = {
        "case_id": clean_id,
        "title": f"Security Research Analysis: {clean_id}",
        "package": clean_id,
        "version": "latest",
        "ecosystem": "npm",
        "severity": "high",
        "summary": "Automated AST differential analysis identified suspicious behaviors in package release.",
        "evidence": [],
        "iocs": [],
        "diff_summary": "Ast-aware static heuristics flagged unexpected payload.",
        "baseline_version": "previous release",
    }

    with soc_store.connect(db_path) as conn:
        row = conn.execute("SELECT * FROM research_cases WHERE case_id = ?", (clean_id,)).fetchone()
        if row:
            case_row = dict(row)
            case_data["title"] = str(case_row.get("title") or case_data["title"])
            case_data["summary"] = str(case_row.get("summary") or case_data["summary"])
            case_data["severity"] = str(case_row.get("severity") or case_data["severity"])

            subject = conn.execute("SELECT * FROM research_subjects WHERE case_id = ? LIMIT 1", (clean_id,)).fetchone()
            if subject:
                subj_dict = dict(subject)
                case_data["package"] = str(subj_dict.get("name") or case_data["package"])
                case_data["ecosystem"] = str(subj_dict.get("ecosystem") or case_data["ecosystem"])
                case_data["version"] = str(subj_dict.get("version") or case_data["version"])

            for ioc_row in conn.execute("SELECT value FROM research_iocs WHERE case_id = ?", (clean_id,)).fetchall():
                case_data["iocs"].append(str(ioc_row["value"]))

            for evd_row in conn.execute("SELECT title, sha256 FROM research_evidence WHERE case_id = ? LIMIT 5", (clean_id,)).fetchall():
                title = str(evd_row["title"] or "")
                sha = str(evd_row["sha256"] or "")
                if title:
                    case_data["evidence"].append(f"{title} (SHA: {sha[:16]}...)" if sha else title)
        else:
            f_row = conn.execute("SELECT * FROM findings WHERE finding_id = ?", (clean_id,)).fetchone()
            if f_row:
                f_dict = dict(f_row)
                case_data["title"] = str(f_dict.get("title") or case_data["title"])
                case_data["summary"] = str(f_dict.get("summary") or case_data["summary"])
                case_data["package"] = str(f_dict.get("package") or case_data["package"])
                case_data["ecosystem"] = str(f_dict.get("ecosystem") or case_data["ecosystem"])
                case_data["version"] = str(f_dict.get("new_version") or f_dict.get("version") or "")
                case_data["baseline_version"] = str(f_dict.get("old_version") or "")
                case_data["severity"] = str(f_dict.get("severity") or case_data["severity"])

    pack_id = f"CPK-{clean_id}"
    base_dir = content_packs_dir(output_dir) / pack_id
    base_dir.mkdir(parents=True, exist_ok=True)
    assets_dir = base_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)

    twitter_content = _format_twitter_thread(case_data)
    reddit_content = _format_reddit_post(case_data)
    linkedin_content = _format_linkedin_post(case_data)

    (base_dir / "twitter_thread.md").write_text(twitter_content, encoding="utf-8")
    (base_dir / "reddit_post.md").write_text(reddit_content, encoding="utf-8")
    (base_dir / "linkedin_post.md").write_text(linkedin_content, encoding="utf-8")

    evd_txt = "\n".join([f"[!] HIT: {item}" for item in case_data["evidence"]]) if case_data["evidence"] else "[!] Flagged: Obfuscated eval and outbound network communication"
    diff_asset = f"""================================================================================
SECOPSAI AST DIFFERENTIAL SNAPSHOT
Target: {case_data["package"]}@{case_data["version"]} ({case_data["ecosystem"]})
Comparison: Baseline ({case_data.get("baseline_version")}) -> Target ({case_data.get("version")})
================================================================================
{evd_txt}
================================================================================
"""
    (assets_dir / "01_ast_diff.txt").write_text(diff_asset, encoding="utf-8")

    attack_flow = f"""[1. Ingestion] -> [{case_data["ecosystem"]} Registry Feed]
[2. AST Parser] -> [Identified anomalous execution sink]
[3. Diff Engine] -> [0 benign delta, high-entropy payload]
[4. Verdict] -> [MALICIOUS ISOLATION]
"""
    (assets_dir / "02_attack_flow.txt").write_text(attack_flow, encoding="utf-8")
    (assets_dir / "03_iocs.json").write_text(json.dumps(case_data["iocs"], indent=2), encoding="utf-8")

    manifest = {
        "pack_id": pack_id,
        "case_id": clean_id,
        "created_at": _now(),
        "package": case_data["package"],
        "ecosystem": case_data["ecosystem"],
        "version": case_data["version"],
        "severity": case_data["severity"],
        "content": {
            "twitter_thread": twitter_content,
            "reddit_post": reddit_content,
            "linkedin_post": linkedin_content,
        },
        "files": {
            "twitter_thread": str(base_dir / "twitter_thread.md"),
            "reddit_post": str(base_dir / "reddit_post.md"),
            "linkedin_post": str(base_dir / "linkedin_post.md"),
            "assets": [str(p) for p in assets_dir.glob("*")],
        },
    }
    (base_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def list_content_packs(*, output_dir: Optional[str] = None) -> List[Dict[str, Any]]:
    """List all available content packs."""
    base = content_packs_dir(output_dir)
    packs: List[Dict[str, Any]] = []
    for path in sorted(base.glob("CPK-*"), reverse=True):
        if not path.is_dir():
            continue
        manifest_file = path / "manifest.json"
        if manifest_file.exists():
            try:
                pack_data = json.loads(manifest_file.read_text(encoding="utf-8"))
                if "content" not in pack_data:
                    pack_data["content"] = {}
                    for key, fname in [("twitter_thread", "twitter_thread.md"), ("reddit_post", "reddit_post.md"), ("linkedin_post", "linkedin_post.md")]:
                        fpath = path / fname
                        if fpath.exists():
                            pack_data["content"][key] = fpath.read_text(encoding="utf-8")
                packs.append(pack_data)
            except Exception:
                continue
    return packs
